Repository pagopa/pagopa-afm-marketplace-be, pull requests merged in 2022-09, with the labels that each got.

#35 fix AFM_CALCULATOR_HOST
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: bug

#37 Pipeline Template and more...
  .devops/deploy-pipelines.yml
  .github/workflows/anchore.yml
  Dockerfile
  docker/applicationinsights.json
  docker/run.sh
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: ignore-for-release

#41 [PGEC-65] Async data workflow
  .devops/deploy-pipelines.yml
  api-test/AFM - Azure Dev.postman_environment.json
  api-test/AFM Marketplace.postman_collection.json
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/afm/marketplacebe/config/FeignConfig.java
  src/main/java/it/pagopa/afm/marketplacebe/config/SchedulerConfig.java
  src/main/java/it/pagopa/afm/marketplacebe/config/SwaggerConfig.java
  src/main/java/it/pagopa/afm/marketplacebe/controller/CiController.java
  src/main/java/it/pagopa/afm/marketplacebe/controller/HomeController.java
  src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java
  src/main/java/it/pagopa/afm/marketplacebe/exception/AppError.java
  src/main/java/it/pagopa/afm/marketplacebe/model/CalculatorInfoConfiguration.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/main/java/it/pagopa/afm/marketplacebe/service/CalculatorService.java
  src/main/java/it/pagopa/afm/marketplacebe/task/BundleOfferTaskExecutor.java
  src/main/java/it/pagopa/afm/marketplacebe/task/BundleRequestTaskExecutor.java
  src/main/java/it/pagopa/afm/marketplacebe/task/BundleTaskExecutor.java
  src/main/java/it/pagopa/afm/marketplacebe/task/CalculatorDataTaskExecutor.java
  src/main/java/it/pagopa/afm/marketplacebe/task/CalculatorTaskExecutor.java
  src/main/java/it/pagopa/afm/marketplacebe/task/CiBundleTaskExecutor.java
  src/main/java/it/pagopa/afm/marketplacebe/task/SchedulerTask.java
  src/main/java/it/pagopa/afm/marketplacebe/task/TaskManager.java
  src/main/java/it/pagopa/afm/marketplacebe/util/AzuriteStorageUtil.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/pagopa/afm/marketplacebe/controller/HomeControllerTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
  src/test/java/it/pagopa/afm/marketplacebe/task/ArchiveBundleTaskTest.java
  src/test/resources/application.properties
Labels: enhancement

#42 fix azurite
  src/main/java/it/pagopa/afm/marketplacebe/task/CalculatorDataTaskExecutor.java
Labels: ignore-for-release
