Repository pagopa/pagopa-afm-marketplace-be, pull requests merged in 2022-07, with the labels that each got.

#18 fix: add docker required files
  docker/applicationinsights.json
  docker/run.sh
Labels: bug

#20 Rule R1
  .devops/code-review-pipelines.yml
  pom.xml
  src/main/java/it/pagopa/afm/marketplacebe/config/CosmosDBConfig.java
  src/main/java/it/pagopa/afm/marketplacebe/controller/CiController.java
  src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/Bundle.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/BundleType.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/PaymentMethod.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/Touchpoint.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/TransferCategoryRelation.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleAttribute.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleDetailsAttributes.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleRequest.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/Bundles.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/CiBundleAttribute.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/CiBundleDetails.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/PspBundleDetails.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/CiBundleRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/test/java/it/pagopa/afm/marketplacebe/MarketplaceBeApplicationTests.java
  src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/config/MockitoConfig.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
  src/test/resources/application.properties
Labels: ignore-for-release

#21 [PPR-345]: Add rules R2 R4
  src/main/java/it/pagopa/afm/marketplacebe/controller/HomeController.java
  src/main/java/it/pagopa/afm/marketplacebe/model/request/CiBundleSubscriptionRequest.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleRequestServiceTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Labels: enhancement

#22 [PPR-345] Rule R7
  doc/entities.puml
  src/main/java/it/pagopa/afm/marketplacebe/model/request/CiBundleSubscriptionRequest.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java
  src/main/java/it/pagopa/afm/marketplacebe/util/CommonUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleRequestServiceTest.java
Labels: ignore-for-release

#26 [PGEC-41] Rule R10
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Labels: bug

#28 [PGEC-39] Add validitydate check
  src/main/java/it/pagopa/afm/marketplacebe/config/LoggingAspect.java
  src/main/java/it/pagopa/afm/marketplacebe/config/RequestFilter.java
  src/main/java/it/pagopa/afm/marketplacebe/controller/CiController.java
  src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/ArchivedBundleRequest.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/Bundle.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/BundleOffer.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/BundleRequestEntity.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/CiBundle.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/CiBundleAttribute.java
  src/main/java/it/pagopa/afm/marketplacebe/model/AppCorsConfiguration.java
  src/main/java/it/pagopa/afm/marketplacebe/model/AppInfo.java
  src/main/java/it/pagopa/afm/marketplacebe/model/PageInfo.java
  src/main/java/it/pagopa/afm/marketplacebe/model/ProblemJson.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleAttribute.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleAttributeResponse.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleDetailsAttributes.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleRequest.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleResponse.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/Bundles.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/CiBundleAttribute.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/CiBundleDetails.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/CiBundleInfo.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/CiBundles.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/PspBundleDetails.java
  src/main/java/it/pagopa/afm/marketplacebe/model/offer/BundleCiOffers.java
  src/main/java/it/pagopa/afm/marketplacebe/model/offer/BundleOffered.java
  src/main/java/it/pagopa/afm/marketplacebe/model/offer/BundleOffers.java
  src/main/java/it/pagopa/afm/marketplacebe/model/offer/CiBundleId.java
  src/main/java/it/pagopa/afm/marketplacebe/model/offer/CiBundleOffer.java
  src/main/java/it/pagopa/afm/marketplacebe/model/offer/PspBundleOffer.java
  src/main/java/it/pagopa/afm/marketplacebe/model/request/BundleRequestId.java
  src/main/java/it/pagopa/afm/marketplacebe/model/request/CiBundleAttributeModel.java
  src/main/java/it/pagopa/afm/marketplacebe/model/request/CiBundleRequest.java
  src/main/java/it/pagopa/afm/marketplacebe/model/request/CiRequests.java
  src/main/java/it/pagopa/afm/marketplacebe/model/request/PspBundleRequest.java
  src/main/java/it/pagopa/afm/marketplacebe/model/request/PspCiBundleAttribute.java
  src/main/java/it/pagopa/afm/marketplacebe/model/request/PspRequests.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Labels: enhancement

#27 [PGEC-43] Rule R12
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java
  src/main/java/it/pagopa/afm/marketplacebe/util/CommonUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleOfferServiceTest.java
Labels: ignore-for-release

#29 [PGEC-42] Rule R11
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java
Labels: ignore-for-release
