Repository pagopa/pagopa-afm-marketplace-be, pull requests merged in 2023-03, with the labels that each got.

#60 [PAGOPA-756] Payment type upload bug
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/afm/marketplacebe/controller/PaymentTypeController.java
  src/main/java/it/pagopa/afm/marketplacebe/exception/AppError.java
  src/main/java/it/pagopa/afm/marketplacebe/service/PaymentTypeService.java
  src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/controller/PaymentTypeControllerTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/PaymentTypeServiceTest.java
Labels: enhancement

#61 fix: [PAGOPA-767] Nullable field
  src/main/java/it/pagopa/afm/marketplacebe/entity/Bundle.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleRequest.java
Labels: bug

#63 fix mapping
  src/main/java/it/pagopa/afm/marketplacebe/entity/ArchivedBundleOffer.java
  src/main/java/it/pagopa/afm/marketplacebe/task/ValidBundlesTaskExecutor.java
Labels: bug

#64 [PAGOPA-731] CRUD sync payment type
  src/main/java/it/pagopa/afm/marketplacebe/controller/PaymentTypeController.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/PaymentType.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/main/java/it/pagopa/afm/marketplacebe/service/PaymentTypeService.java
  src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/controller/PaymentTypeControllerTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/PaymentTypeServiceTest.java
Labels: enhancement

#66 fix: resolved bug on wrong sync for payment types
  src/main/java/it/pagopa/afm/marketplacebe/service/PaymentTypeService.java
  src/test/java/it/pagopa/afm/marketplacebe/service/PaymentTypeServiceTest.java
Labels: bug

#65 [PAGOPA-673] Opex
  .github/workflows/anchore.yml
  .github/workflows/assignee.yml
  .github/workflows/check_metadata_pr.yml
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/deploy.yml
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  .github/workflows/self_hosted.yml
  .github/workflows/sonar_analysis.yml
  .github/workflows/update_code.yml
  .github/workflows/update_infra.yml
  .gitignore
  .identity/.terraform.lock.hcl
  .identity/00_locals.tf
  .identity/00_main.tf
  .identity/00_variables.tf
  .identity/01_data.tf
  .identity/02_application_action.tf
  .identity/02_application_action_auth.tf
  .identity/03_github_environment.tf
  .identity/99_outputs.tf
  .identity/env/dev/backend.ini
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.ini
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.ini
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  .identity/terraform.sh
  .opex/env/prod/backend.ini
  .opex/env/prod/backend.tfvars
  .opex/env/prod/config.yaml
  .opex/env/prod/terraform.tfvars
  helm/charts/microservice-chart-1.21.0.tgz
Labels: ignore-for-release, size/large, skip
