Repository pagopa/pagopa-afm-marketplace-be, pull requests merged in 2024-04, with the labels that each got.

#90 Pagopa 1638 sviluppo filtro idBundle pacchetto
  openapi/openapi.json
  src/main/java/it/pagopa/afm/marketplacebe/controller/CiController.java
  src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java
  src/main/java/it/pagopa/afm/marketplacebe/exception/ErrorHandler.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRequestRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleRequestServiceTest.java
Labels: bug, enhancement, size/small

#91 Pagopa 1614 afm marketplace get bundle
  openapi/generate_openapi.sh
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRequestRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/CiBundleRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/test/java/it/pagopa/afm/marketplacebe/OpenApiGenerationTest.java
  src/test/java/it/pagopa/afm/marketplacebe/controller/PspControllerTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleRequestServiceTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Labels: enhancement, size/small

#92 Pagopa 1619 sviluppo afm market place ricerca bundle per psp company name
  openapi/openapi.json
  src/main/java/it/pagopa/afm/marketplacebe/controller/CiController.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/CiBundleRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/controller/CiControllerTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Labels: enhancement, size/small

#96 [VAS-945] chore: Update get bundle ci details API
  openapi/openapi.json
  src/main/java/it/pagopa/afm/marketplacebe/config/MappingsConfiguration.java
  src/main/java/it/pagopa/afm/marketplacebe/mapper/ConvertCIBundleTCIBundleDetails.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/CiBundleDetails.java
  src/main/java/it/pagopa/afm/marketplacebe/model/offer/BundleCreditorInstitutionResource.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Labels: size/small

#99 chore: Github_federated_identity
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/integration_test.yml
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
Labels: ignore-for-release, size/small
