Repository pagopa/pagopa-afm-marketplace-be, pull requests merged in 2024-05, with the labels that each got.

#101 [VAS-1005] fix: Bundle request model mapping
  openapi/openapi.json
  src/main/java/it/pagopa/afm/marketplacebe/model/request/PublicBundleRequest.java
  src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
Labels: size/small

#98 PAGOPA-1675 allineamento schema ER
  doc/entities.puml
Labels: size/small

#97 PAGOPA-1666 adding openapi technical support creation
  openapi/generate_openapi.sh
  openapi/openapi-technical-support.json
  openapi/openapi.json
Labels: enhancement, ignore-for-release, size/large

#105 [VAS-1034] feat: Add check on create public bundle request
  src/main/java/it/pagopa/afm/marketplacebe/exception/AppError.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleRequestServiceTest.java
Labels: enhancement

#106 PAGOPA-1759 fixing null attributes when accepting an offer
  openapi/openapi.json
  src/main/java/it/pagopa/afm/marketplacebe/exception/AppError.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleOfferServiceTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Labels: bug, size/small, patch
