Repository pagopa/pagopa-afm-marketplace-be, pull requests merged in 2024-06, with the labels that each got.

#109 [VAS-1075] feat: Update get offers API
  openapi/openapi.json
  src/main/java/it/pagopa/afm/marketplacebe/config/SwaggerConfig.java
  src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/BundleOfferRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/main/java/it/pagopa/afm/marketplacebe/util/CommonUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/controller/PspControllerTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleOfferServiceTest.java
  src/test/resources/application.properties
Labels: enhancement, minor

#111 fix: Swagger config
  src/main/java/it/pagopa/afm/marketplacebe/config/SwaggerConfig.java
Labels: bug, size/small, patch

#112 [VAS-1080] feat: Add get bundle detail API for CI
  openapi/openapi.json
  src/main/java/it/pagopa/afm/marketplacebe/controller/BundleController.java
  src/main/java/it/pagopa/afm/marketplacebe/controller/CiController.java
  src/main/java/it/pagopa/afm/marketplacebe/controller/HomeController.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/BundleOfferRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/CosmosRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/test/java/it/pagopa/afm/marketplacebe/controller/BundleControllerTest.java
  src/test/java/it/pagopa/afm/marketplacebe/controller/CiControllerTest.java
  src/test/java/it/pagopa/afm/marketplacebe/controller/HomeControllerTest.java
  src/test/java/it/pagopa/afm/marketplacebe/repository/CosmosRepositoryTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleOfferServiceTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Labels: enhancement, size/large, minor

#114 [VAS-1105] feat: Update accept offer API
  openapi/openapi.json
  src/main/java/it/pagopa/afm/marketplacebe/controller/CiController.java
  src/main/java/it/pagopa/afm/marketplacebe/exception/AppError.java
  src/main/java/it/pagopa/afm/marketplacebe/model/request/CiBundleAttributeModel.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java
  src/test/java/it/pagopa/afm/marketplacebe/controller/CiControllerTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleOfferServiceTest.java
Labels: enhancement, size/large, minor

#116 feat: Added force update bundle parameter
  openapi/openapi.json
  src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/test/java/it/pagopa/afm/marketplacebe/controller/PspControllerTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Labels: size/small

#115 [VAS-1109] feat: Update get bundles API
  openapi/openapi.json
  src/main/java/it/pagopa/afm/marketplacebe/controller/BundleController.java
  src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java
  src/main/java/it/pagopa/afm/marketplacebe/mapper/ConvertBundleToPspBundleDetails.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/PspBundleDetails.java
  src/main/java/it/pagopa/afm/marketplacebe/repository/CosmosRepository.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/test/java/it/pagopa/afm/marketplacebe/controller/BundleControllerTest.java
  src/test/java/it/pagopa/afm/marketplacebe/repository/CosmosRepositoryTest.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Labels: enhancement, minor

#117 [PAGOPA-1877] feat: cart bundle management
  openapi/openapi.json
  src/main/java/it/pagopa/afm/marketplacebe/entity/Bundle.java
  src/main/java/it/pagopa/afm/marketplacebe/mapper/ConvertBundleToPspBundleDetails.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleRequest.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/PspBundleDetails.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/main/java/it/pagopa/afm/marketplacebe/task/ValidBundlesTaskExecutor.java
  src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
Labels: size/small
