Repository pagopa/pagopa-afm-marketplace-be, pull requests merged in 2025-03, with the labels that each got.

#122 [PIDM-61] Include bundle type check in transfer category list validation
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Labels: size/small, patch

#123 feat: [PAGOPA-2659] Define script to patch all bundles with new field onus
  .github/workflows/code_review.yml
  .gitignore
  utilities/patchOnUsBundles/package.json
  utilities/patchOnUsBundles/script.js
Labels: skip, size/small

#124 feat: [PAGOPA-2657] Add onUs flag to bundles
  openapi/openapi-technical-support.json
  openapi/openapi.json
  src/main/java/it/pagopa/afm/marketplacebe/entity/ArchivedBundle.java
  src/main/java/it/pagopa/afm/marketplacebe/entity/Bundle.java
  src/main/java/it/pagopa/afm/marketplacebe/mapper/ConvertBundleToPspBundleDetails.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleRequest.java
  src/main/java/it/pagopa/afm/marketplacebe/model/bundle/PspBundleDetails.java
  src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
  src/main/java/it/pagopa/afm/marketplacebe/task/ValidBundlesTaskExecutor.java
  src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
  src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Labels: size/small, patch

#125 fix: update pat token secret in repo
  .identity/00_data.tf
  .identity/03_github_environment.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi-technical-support.json
  openapi/openapi.json
  pom.xml
Labels: bug, ignore-for-release, skip, size/small
